### ISSUE TITLE
using .vcmrc file returns 'true' even for invalid commit messages

### ISSUE THREAD

**Issue by Alice-anjali** [conventional-changelog/validate-commit-msg#113]
I followed all the steps provided in the documentation and used .vcmrc file for configuration. It returns 'true' for both valid and invalid commit messages along with a log message for invalid commits.
![screenshot from 2017-07-16 01-15-23](https://user-images.githubusercontent.com/20883037/29002169-2ec51538-7aba-11e7-804b-6c4bb6a0d785.png)

I tried again after removing .vcmrc file. It works fine, returns 'false' for invalid commits and logs and error message with the commits
![without_pkg](https://user-images.githubusercontent.com/20883037/29002179-611553ea-7aba-11e7-8329-e19be5d8c1b1.png)

I didn't wanted the log messages. So, I used the second method given for configuration which was to write configuration in package.json
![pkg](https://user-images.githubusercontent.com/20883037/29002190-99027f76-7aba-11e7-9746-7922cfba1caf.png)
"warnOnFail" is false, so it should not log the error messages. But it still logs those messages
![using_pkg](https://user-images.githubusercontent.com/20883037/29002196-bf18dbe2-7aba-11e7-8978-76e66ee27795.png)

I am not able to understand this. I might be doing something wrong. Please help me :-)

**Comment by cmalard** [comment]
Hi @Alice-anjali ,

>warnOnFail
>If this is set to true errors will be logged to the console, however the commit will still pass.

`.vcmrc` has precedence over config in `package.json`, so if you set `warnOnFail: true`, looks like it did what you asked

**Comment by Alice-anjali** [comment]
Hey @cmalard.. thanks for replying :-)
I have 2 doubts. As you can see, I have mentioned that I used .vcmrc file first. But on checking the commit messages, it returns 'true' for both valid and invalid commits [This is my first doubt]. So, I removed .vcmrc file and tried again, it works fine, but it's logging error messages for invalid commits which I don't want. That's when I wrote configurations in package.json file and set wornOnFail: false (I have posted the screenshot above). It should not log error messages now but it's still logging [This is my second doubt].

**Comment by cmalard** [comment]
There is no option to stop validate-commit-msg from logging errors to the console (cf my quote of the doc ;-) )

About your first doubt, could you please provide the `.vcmrc` file you used ?

**Comment by cmalard** [comment]
If your goal is to validate a branch, [try this](https://github.com/cmalard/validate-commit-msg/commit/63e4c8d72f187fa9673abb881f1b5f0a57000525) :-)

**Comment by Alice-anjali** [comment]
I understood what you said about warnOnFail. I misread the documentation earlier. My code is running successfully now. 
Sorry for the inconvenience and thanks a lot for your help :-D
