### ISSUE TITLE
Add example to log

### ISSUE THREAD

**Issue by gauntface** [conventional-changelog/validate-commit-msg#115]
Just landed on a repo that used this and the default log isn't super helpful to understand what is needed.

Instead of:

```
INVALID COMMIT MSG: does not match "<type>(<scope>): <subject>" !
```

An example would commit would be helpful:

```
INVALID COMMIT MSG: Your commit message must follow the pattern "<type>(<scope>): <subject>".
                                         A valid commit message should look like: "test-fix(my-package): I fixed XYZ"
```

**Comment by Garbee** [comment]
Hello Matt,

I'm currently in the process of deprecating this package and forwarding people over to [commitlint](https://github.com/marionebl/commitlint). Getting things in place for the transition now.

Do you feel this is somewhat-important to be fixed here? Could we focus this kind of feedback over to commitlint instead to get that library's end user experience improved for the longer haul?

Thank you.

**Comment by gauntface** [comment]
Totally makes sense if that's the case, will nudge Firebase to move over ;)

**Comment by Garbee** [comment]
Thanks Matt. I completely see your concern here and I myself would like to see this kind of output for end users. Not everyone knows what the structure means or stands for. I'm simply considering imminent deprecation with improving the recommended library for the better in the same swoop. 

It would be a good bit of work to make sure all the tests are updated properly and that the added output is only in place when needed (as well as properly formatted so it isn't one huge line.)

Thanks for understanding!
