### ISSUE TITLE
Transfer to conventional-changelog

### ISSUE THREAD

**Issue by kentcdodds** [conventional-changelog/validate-commit-msg#88]
I remember someone suggesting that we transfer this repo to the [`conventional-changelog`](https://github.com/conventional-changelog) org. I think that'd be a great idea. I'm not really interested in maintaining this package anymore (I still use it, I just consider it "done" and don't want to keep updating it). Who would be the best point of contact to transfer the repo? Who's interested in maintaining this?

cc @stevemao, @jimthedev, @spirosikmd, @Garbee

**Comment by Garbee** [comment]
Issue #84 was the origination of the discussion on this. I'm open to helping maintain it. I was already looking at doing a ES-2016 update to the base this weekend as well as fixing #83 in the process (since it would end up being a major rev.)

**Comment by kentcdodds** [comment]
@Garbee, what's your npm username? I'll add you to publishers.

**Comment by Garbee** [comment]
Just `garbee` [there](https://www.npmjs.com/~garbee) as well.

**Comment by kentcdodds** [comment]
You're in! 👍 https://www.npmjs.com/package/validate-commit-msg

**Comment by stevemao** [comment]
@Garbee I have invited you to the org. @kentcdodds Would you be able to transfer this repo to the org? https://github.com/conventional-changelog

**Comment by kentcdodds** [comment]
I'm getting:

> You don’t have the permission to create repositories on conventional-changelog

**Comment by stevemao** [comment]
sorry @kentcdodds, I have changed you as an owner. Could you try again?

**Comment by kentcdodds** [comment]
Done!

**Comment by stevemao** [comment]
Thank you @kentcdodds :)

**Comment by kentcdodds** [comment]
Thank you!
