### ISSUE TITLE
Setup autorelease again

### ISSUE THREAD

**Issue by kentcdodds** [conventional-changelog/validate-commit-msg#94]
Because I'm no longer maintaining this package, I decided it would be best for me to delete my npm and github tokens from the travis build and [remove the semantic-release step from `.travis.yml`](https://github.com/conventional-changelog/validate-commit-msg/commit/da9ef5cbbddefea5be7309a57b489e7a2cae9c83). Feel free to [set it up again](https://egghead.io/lessons/javascript-how-to-write-a-javascript-library-automating-releases-with-semantic-release).

If you don't care to autorelease this, then feel free to close this.

**Comment by Garbee** [comment]
I'm working on the V2 update right now. Will keep this open as a reminder to make sure this is all done after that is merged. For now I don't think we'll need the auto-release much since it is mostly documentation changes being submitted currently.

Thank you!

**Comment by maxcnunes** [comment]
@Garbee Could you run a manually release? I was hoping get that [change](https://github.com/conventional-changelog/validate-commit-msg/commit/84864950ad872050acaf12646c79335a76fd6412) in my project. Thanks!!

**Comment by Garbee** [comment]
Ah, yup. Forgot about this on Monday, had an interview. I should be able to get a patch out later this evening or early tomorrow. Thanks for the reminder!

**Comment by nickbalestra** [comment]
Happy to help to set it up again as I see we are some release behind merged PR now.
Do you want the encrypted tokens directly on the `travis.yml` or via travis UI (for the later I guess I need to be added to the org so that I can access travis settings page for this repo)

**Comment by Garbee** [comment]
Sorry, looking at a release of this now. Some emergency stuff came up this week and I haven't been around my computer much.

**Comment by nickbalestra** [comment]
No worries @Garbee, I'm happy to help. 
As semantic-release still there (apart from the cmd script in travis to run it), if you grant me publishing right, I can encrypt both tokens (GH_TOKEN and NPM_TOKEN) in the travis.yml with a PR, that should make it working again. Thoughts?

**Comment by Garbee** [comment]
Access granted on NPM, giving you repo access now to the settings. Thanks for the help here, looks like things are going to be crazy through tomorrow for me. :frowning:

**Comment by Garbee** [comment]
hmm, looks like I don't have repo admin access since the org move. I'll work on that later. Is just NPM push access enough for now to get the job done?

**Comment by nickbalestra** [comment]
Yes it should, as I should be able to encrypt the tokens directly on the `travis.yml` instead of putting them through the travis admin UI, let's try :) And,  thank you!

**Comment by stevemao** [comment]
@Garbee you should be an admin now

**Comment by nickbalestra** [comment]
Mmm, @Garbee  so it seems it successfully published [the release on npm](https://www.npmjs.com/package/validate-commit-msg) but [wasn't able](https://travis-ci.org/conventional-changelog/validate-commit-msg) to publish the release-nots on github.

Could this be related to https://github.com/conventional-changelog/validate-commit-msg/pull/92 and other fixes being merged but not published since auto-release stop working (I don't know semantic-releases works in the case you have some unpublished releases behind....)

**Comment by Garbee** [comment]
Looks like it is from the org move. Looking into it now.

**Comment by Garbee** [comment]
Appears that #103 will fix it by removing the redirect from the old org.

**Comment by Garbee** [comment]
Since the semantic release isn't detecting a relevant change it isn't pushing a new release. So I'll do a manual one and if it doesn't trigger on the next we'll debug it further.

Thank you for the help here @nickbalestra. It's appreciated so much!

**Comment by Garbee** [comment]
And it is pushing now! New release is on GH as well.

**Comment by nickbalestra** [comment]
Awesomeness!!!
