### ISSUE TITLE
[cli] input is ignored, output is misleading

### ISSUE THREAD

**Issue by jiaweihli** [conventional-changelog/validate-commit-msg#96]
The CI docs mention [passing in the commit message](https://github.com/conventional-changelog/validate-commit-msg#ci).  

After trying to set this up in CircleCI, I realized that the CLI completely ignores the input arguments.  It actually reads from the `.git/COMMIT_EDITMSG` file, which is the last edited commit message for that git client.  In a CI environment, this'll be empty because the VM didn't commit anything.

**Comment by stevemao** [comment]
see https://github.com/conventional-changelog/validate-commit-msg/pull/87

**Comment by jiaweihli** [comment]
From the [releases page](https://github.com/conventional-changelog/validate-commit-msg/releases), it looks like my best bet is rolling back to 2.12.1 in the meantime?

**Comment by stevemao** [comment]
I believe https://github.com/conventional-changelog/validate-commit-msg/pull/92 should solve the problem. Feel free to give it a shot :)

**Comment by jiaweihli** [comment]
Cool, I haven't tried it out yet but I've verified 2.12.1 does work.

**Comment by stevemao** [comment]
I'm closing this since https://github.com/conventional-changelog/validate-commit-msg/pull/92#issuecomment-313691307 is merged. Please comment if I'm wrong @maxcnunes @Garbee Thanks.
